services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  # Class registration
  Digicademy\Lod\:
    resource: '../Classes/*'

  # Event Listener
  Digicademy\Lod\EventListener\AfterMappingSingleRow:
    tags:
      - name: event.listener
        identifier: 'after_mapping_single_row'
        event: TYPO3\CMS\Extbase\Event\Persistence\AfterObjectThawedEvent

  # Hooks
  Digicademy\Lod\Hooks\Backend\DataHandler:
    public: true

  # Services
  Digicademy\Lod\Service\ContentNegotiationService:
    public: true
  Digicademy\Lod\Service\ResolverService:
    public: true
  Digicademy\Lod\Service\ItemMappingService:
    public: true

  # We need the to inject the container instance for some dependency fetching,
  # so we need to autowire the container itself.
  TYPO3\CMS\Extbase\Object\Container\Container:

  # the following services are instantiated within a BE hook and need no autowiring
  # Digicademy\Lod\Service\IdentifierGeneratorService:
  # Digicademy\Lod\Service\TableTrackingService:
